講座一覧画面の実装 #58
yukihiroLaravel/juko_next pull request #2
Opened 2022-11-05 01:11 UTC by Hikaru-Giannis

## Issue
Zira :  https://gut-familie.atlassian.net/browse/JKA-58

## やったこと
- CSSフレームワークとして、Tailwindの導入
- 講座一覧画面のデザインコーディング
- LaravelのAPIをするためのproxy対応

## 残タスク
- サムネイルの表示
- 表示までのローディング
- APIエラー処理

## 確認方法
- Nextのコンテナで`npm install`

2022-11-06 02:59 UTC, yukihiroLaravel requested changes
いくつかコメントしました！
お手数ですがご確認願います！！

2022-11-06 02:59 UTC, yukihiroLaravel commented on features/course/CourseCard.tsx
> +          <Image src={'http://laravel_app:80/storage' + course.image} alt="course" height={360} width={640} />
ここですが
なぜか画像にアクセスできません。

もしかして正しくは
laravel_app:8080
ではないでしょうか？
（そのように書き換えてもアクセスできなかったですが...汗）

あと、ポート番号もnext.configもしくはenvファイルで指定できるようにした方が良くないでしょうか？

2022-11-06 02:59 UTC, yukihiroLaravel commented on hooks/useFetchCourses.tsx
> +    Axios.get('api/proxy/api/v1/courses?student_id=1')
ここですが、
api/proxy/api/v1/~
と apiがURIに二重に存在しますが、Nextだと普通のことなのでしょうか？

2022-11-06 02:59 UTC, yukihiroLaravel commented on hooks/useFetchCourses.tsx
> +  setIsError: (value: React.SetStateAction<boolean>) => void
引数の渡し方ですが、
`useFetchCourses({ useFetchCourses, setIsError})`
みたいにオブジェクトで渡せるようにした方が良くないでしょうか？

2022-11-06 02:59 UTC, yukihiroLaravel commented on postcss.config.js
> +    tailwindcss: {},
tailwindは僕も使ったことないですが、今後使われるモダンなCSSなので良いと思います！
必要に応じて、styledComponent も使っていけたら使いやすいかもですね。

2022-11-06 04:44 UTC, Hikaru-Giannis commented on features/course/CourseCard.tsx
> +          <Image src={'http://laravel_app:80/storage' + course.image} alt="course" height={360} width={640} />
自分も最初そのように実装していたのですが、ネットワークが繋がらないとのことで動作確認できなかったです。
Dockerのコンテナ同士の通信が原因として考えられるので、コンテナ側のポート番号を指定することで問題なかったのでそのように実装しました。

検証環境、本番環境はそのようなコンテナのネットワーク通信の問題は発生しない想定です...。

後にenvファイル設定しようと思い、失念しておりました。対応します。

2022-11-06 04:46 UTC, Hikaru-Giannis commented on hooks/useFetchCourses.tsx
> +    Axios.get('api/proxy/api/v1/courses?student_id=1')
ProxyをLaravelの`api/`に限定すれば、おそらく対応できると思うのですが、認証にsanctumを使うのであれば認証系がweb.phpにルーティング設定する必要があった気がするのでそれらの懸念を考慮した実装でした。

2022-11-06 04:58 UTC, Hikaru-Giannis commented on hooks/useFetchCourses.tsx
> +  setIsError: (value: React.SetStateAction<boolean>) => void
こちらはカスタムフックとして実装しています。
引数をオブジェクトにするルールがあるなどは存じていないのですが、オブジェクトの方が良いことなどあるのでしょうか？
こだわりとかはないのでオブジェクトが一般的だったり、今回のプロジェクトのルールではそうするなどであれば対応します！

2022-11-06 05:06 UTC, Hikaru-Giannis commented on features/course/CourseCard.tsx
> +          <Image src={'http://laravel_app:80/storage' + course.image} alt="course" height={360} width={640} />
envファイル化して対応済みです。

2022-11-06 07:16 UTC, yukihiroLaravel commented on hooks/useFetchCourses.tsx
> +  setIsError: (value: React.SetStateAction<boolean>) => void
引数をオブジェクトに絶対しないとイケないわけではないですが、
カスタムフックに限らず、引数が２つ以上ある関数の場合、
順序で第一引数・第二引数の役割を分けるより、
オブジェクトを利用した方が、引数の役割が明示的で分かりやすく
モダンな現場ではそうなってきている印象（個人の見解も含む）なので指摘しました！

可能であれば対応いただければと思います☺️

2022-11-06 07:16 UTC, yukihiroLaravel commented on hooks/useFetchCourses.tsx
> +    Axios.get('api/proxy/api/v1/courses?student_id=1')
かしこまりました！
一旦これでOKです！

2022-11-06 07:20 UTC, yukihiroLaravel commented on features/course/CourseCard.tsx
> +          <Image src={'http://laravel_app:80/storage' + course.image} alt="course" height={360} width={640} />
ご対応ありがとうございます！
こちらこれでOKです！

2022-11-07 09:40 UTC, yukihiroLaravel approved these changes
完璧です。
LGTMです！！マージしました！

2022-11-07 09:41 UTC, merged