チャプター&レッスン画面の実装。 #60
yukihiroLaravel/juko_next pull request #3
Opened 2022-11-14 10:09 UTC by Hikaru-Giannis

## Issue
zira: https://gut-familie.atlassian.net/browse/JKA-60

## やったこと
チャプター&レッスン画面の見た目の実装。

## 確認方法
http://localhost:3000/course にアクセス。
Figma URL: https://www.figma.com/file/Hsb83saiTsDZrNCKsumzzO/%E5%8F%97%E8%AC%9B%E3%82%A2%E3%83%97%E3%83%AA?node-id=0%3A1

## 考慮事項
- APIからの取得はまだ未実装。

2022-11-15 07:29 UTC, yukihiroLaravel commented on features/lesson/components/StatusIcon.tsx
> +            stroke-width="2"
ここ`strokeWith`にしていないので、
エラーにはなっていないですが、warningが出ていました！

2022-11-15 07:52 UTC, yukihiroLaravel requested changes
ほぼデザイン通りに作成されていて
再現度が素晴らしいですね✨

いくつか指摘しましたので
お手数ですがご確認ください☺️

2022-11-15 07:52 UTC, yukihiroLaravel commented on components/utils/ClosedToggleButton.tsx
> +};
ボタンやバー、サムネイルなどの共通コンポーネントを
utilsに置いた理由は何かありますでしょうか？

下記の例のように共通コンポーネントは
`/components/elements`
などに配置した方がいいかな？と個人的に思いました！
https://zenn.dev/yodaka/articles/eca2d4bf552aeb

2022-11-15 07:52 UTC, yukihiroLaravel commented on components/utils/OpenedToggleButton.tsx
> +};
こちら、ClosedToggleButtonとOpenedToggleButton をまとめて１つのコンポーネントにできませんか？

2022-11-15 07:52 UTC, yukihiroLaravel commented on pages/course.tsx
> +                  width={640}
下記のように、スマホサイズにすると潰れちゃいますね。。。！

（スマホ画面デザインは決めていませんでしたが）
スマホサイズのときは、
サイドメニュー部分は1番上に来るようにした方がいいかもですね！
<img width="385" alt="スクリーンショット 2022-11-15 16 45 55" src="https://user-images.githubusercontent.com/93365035/201860614-823b5dc5-8d77-456f-9f0e-e142ab08c55d.png">

2022-11-17 13:29 UTC, kou-tech commented on components/utils/ClosedToggleButton.tsx
> +};
自分が参考にしたディレクトリ構成がそのようにしていたためでした！
意図としては同じなので移植します。

2022-11-17 13:29 UTC, Hikaru-Giannis commented on components/utils/OpenedToggleButton.tsx
> +};
かしこまりました！

2022-11-17 13:31 UTC, Hikaru-Giannis commented on pages/course.tsx
> +                  width={640}
スマホの場合で、サイドバーをメインコンテンツに重ねる術を調べても分からなかったためご存じでしたら教えていただきたいです...。

2022-11-20 03:35 UTC, yukihiroLaravel commented on pages/course.tsx
> +                  width={640}
修正ありがとうございます！
良い感じですね！

ただ、２点ほど気になった点があります🙇‍♂️

・講座名とカリキュラムがくっついているように感じるので
　講座名とカリキュラムの間に、横線を入れる&マージンを取るなどして
　それぞれ分離させた方がいいかなと思いました！

・スマホサイズにしたときに、Lesson1 などの横の進捗マークが
　縦長の丸になっているように見えるので修正いただければ・・・！

ご確認お願いします！

<img width="414" alt="スクリーンショット 2022-11-20 12 28 35" src="https://user-images.githubusercontent.com/93365035/202881403-15601b61-8ca6-49e3-a27a-d018942c0167.png">

2022-11-20 03:49 UTC, yukihiroLaravel requested changes
修正ありがとうございます！
使い回ししやすく作っていただいていると思います☺️

１点気になった点がありましたのでコメントしております！
ご確認ください😊

2022-11-20 03:49 UTC, yukihiroLaravel commented on pages/course.tsx
> +          </div>
サイドメニュー修正ありがとうございます！
良い感じですね！

ただ、２点ほど気になった点があります🙇‍♂️

・講座名とカリキュラムがくっついているように感じるので
　講座名とカリキュラムの間に、横線を入れる&マージンを取るなどして
　それぞれ分離させた方がいいかなと思いました！

・スマホサイズにしたときに、Lesson1 などの横の進捗マークが
　縦長の丸になっているように見えるので修正いただければ・・・！

ご確認お願いします！

<img width="414" alt="スクリーンショット 2022-11-20 12 28 35" src="https://user-images.githubusercontent.com/93365035/202881403-15601b61-8ca6-49e3-a27a-d018942c0167.png">

2022-11-20 09:16 UTC, yukihiroLaravel approved these changes
ありがとうございます！！
OKですので、マージしました☺️

2022-11-20 09:16 UTC, merged