レッスン画面の実装 # 63
yukihiroLaravel/juko_next pull request #4
Opened 2022-11-28 16:32 UTC by Hikaru-Giannis

## Issue
ziraのURL
https://gut-familie.atlassian.net/browse/JKA-63

## 実装内容
- レッスン画面の見た目のコーディング

## 確認方法
- 動画コンテンツ表示のためのライブラリをインストール
  - `npm install`
  - `npm run dev`
- http://localhost:3000/chapter にURLへアクセス

## 共有事項
- 動画コンテンツのレスポンシブ対応のために、画面サイズ取得フックを実装。
- 初回段階はYoutubeを想定しているとのことで、一旦Youtubeの動画IDを指定して表示できるライブラリで実装。

2022-11-30 05:25 UTC, yukihiroLaravel requested changes
いくつかコメントしました！
非常に綺麗に作っていただいていると思います！☺️

あと冒頭に書いていただいている実行すべきコマンドは
npm じゃなくて yarn ですよね？

2022-11-30 05:25 UTC, yukihiroLaravel commented on pages/chapter.tsx
> +                width={(width as number) > 640 ? 1280 : 320}
こちらで高さなどを指定できるのですね！

この数字の意図はありますでしょうか？

見やすく大きめに作っていただいていますが
ノートパソコンやタブレットの画面幅・高さを考慮して、
もっと最大幅と高さを小さくしても良いかなと思いました。

・画面幅1000pxくらいでサイドメニューを開いた状態で動画サムネ全体が見える動画幅に
・画面高さ750pxくらいでレッスンタイトルと動画サムネ全体が見える動画高さに

2022-11-30 05:25 UTC, yukihiroLaravel commented on pages/course.tsx
> +            <TitleStatusCard status="completed" title="Lesson3" />
可能であれば、こちらクリックしたときにレッスン画面に遷移するように、仮の画面遷移リンクを貼っていただければありがたいです！

2022-11-30 05:25 UTC, yukihiroLaravel commented on features/lesson/components/StatusButton.tsx
> +    font-size: 13px;
styled component良いですね！

2022-11-30 05:25 UTC, yukihiroLaravel commented on features/lesson/components/StatusIcon.tsx
> +  };
汎用性高くて素晴らしいですね！

ただ、s や m という文字列だとわかりづらいので
'small', 'medium'とかの方がわかりやすそうですね！

2022-11-30 05:25 UTC, yukihiroLaravel commented on features/lesson/components/StatusIcon.tsx
> +`;
単に場所の問題ですが、
これらはファイルの上の方に配置することが多い気がするのですが
いかがでしょうか？

2023-01-07 04:43 UTC, Hikaru-Giannis commented on pages/chapter.tsx
> +                width={(width as number) > 640 ? 1280 : 320}
たしか、Youtubeのサムネイルサイズに合わせての数値だった気がします！

2023-01-08 08:10 UTC, Hikaru-Giannis commented on pages/course.tsx
> +            <TitleStatusCard status="completed" title="Lesson3" />
かしこまりました！仮のURLを設定して修正済みです！

2023-01-08 08:10 UTC, Hikaru-Giannis commented on features/lesson/components/StatusIcon.tsx
> +  };
確認ありがとうございます！
上記の内容で実装して修正済みです！

2023-01-08 08:11 UTC, Hikaru-Giannis commented on features/lesson/components/StatusIcon.tsx
> +`;
あまり記述箇所を意識していなかったので、気づきませんでした！
一般的にそうようであるということで、修正してプッシュ済みです！

2023-01-10 22:22 UTC, yukihiroLaravel commented on pages/chapter.tsx
> +                width={(width as number) > 640 ? 1280 : 320}
なるほどです！YouTubeの仕様にあわせててですね！

できればユーザーがより使いやすいように変えて欲しいので
少しお手数ではありますが、下記のように変更いただいてもいいでしょうか？

・画面幅1000pxくらいでサイドメニューを開いた状態で動画サムネ全体が見える動画幅に
・画面高さ750pxくらいでレッスンタイトルと動画サムネ全体が見える動画高さに

2023-01-10 22:24 UTC, yukihiroLaravel requested changes
動画の表示サイズの件でコメントしましたので
修正いただければ助かります！

お手数ですが宜しくお願いします☺️

2023-01-13 21:30 UTC, Hikaru-Giannis commented on pages/chapter.tsx
> +                width={(width as number) > 640 ? 1280 : 320}
かしこまりました！
幅を優先に 1024 * 576 としてみましたので、ご確認のほどよろしくお願いします。

2023-01-14 07:38 UTC, yukihiroLaravel commented on pages/chapter.tsx
> +                width={(width as number) > 640 ? 1280 : 320}
ありがとうございます！

ですが、

・画面幅1000pxくらいでサイドメニューを開いた状態で動画サムネ全体が見える動画幅になっていない
<img width="1021" alt="スクリーンショット 2023-01-14 16 33 35" src="https://user-images.githubusercontent.com/93365035/212461603-6596e0e3-8f03-465a-9397-adba45916102.png">

・画面高さ750pxくらいでレッスンタイトルと動画サムネ全体が見える動画高さになっていない
<img width="1025" alt="スクリーンショット 2023-01-14 16 37 58" src="https://user-images.githubusercontent.com/93365035/212461665-4bfecf84-a6b7-410c-9e00-184488de2e07.png">

ように見えるのですが、いかがでしょうか？

2023-01-14 07:41 UTC, yukihiroLaravel requested changes
ありがとうございます！

ですが、写真添えてコメントしたとおり

・画面幅1000pxくらいでサイドメニューを開いた状態で動画サムネ全体が見える動画幅になっていない
・画面高さ750pxくらいでレッスンタイトルと動画サムネ全体が見える動画高さになっていない

となっているように見えるのですがいかがでしょうか？

2023-01-14 07:41 UTC, yukihiroLaravel commented on components/elements/Movie.tsx
> +  return <YouTube videoId={videoId} opts={option} />;
ありがとうございます！

ですが、

・画面幅1000pxくらいでサイドメニューを開いた状態で動画サムネ全体が見える動画幅になっていない
<img width="1021" alt="スクリーンショット 2023-01-14 16 33 35" src="https://user-images.githubusercontent.com/93365035/212461725-79ae5cfb-2b15-4362-813c-d4e615e7158a.png">

・画面高さ750pxくらいでレッスンタイトルと動画サムネ全体が見える動画高さになっていない
<img width="1025" alt="スクリーンショット 2023-01-14 16 37 58" src="https://user-images.githubusercontent.com/93365035/212461731-c060e174-8143-4102-b119-9ae8da6c3f55.png">

ように見えるのですが、いかがでしょうか？

2023-01-15 09:43 UTC, Hikaru-Giannis commented on pages/chapter.tsx
> +                width={(width as number) > 640 ? 1280 : 320}
指摘箇所について、誤った認識をしておりました...。
下記のようにレスポンシブ対応してみたのですが、いかがでしょうか？
![スクリーンショット 2023-01-15 18 42 48](https://user-images.githubusercontent.com/64859506/212533821-873bc8b2-39b7-4005-8b99-a1367d819cb1.png)

2023-01-17 01:58 UTC, yukihiroLaravel approved these changes
ありがとうございます！！
LGTMなのでマージしました！☺️

2023-01-17 01:58 UTC, merged