add:講師側 受講生一覧の受講生検索機能の実装
yukihiroLaravel/juko_next pull request #43
Opened 2024-03-08 13:39 UTC by kaji514

## issue
https://gut-familie.atlassian.net/browse/JKA-755

## 概要
React 講師側 受講生一覧の受講生検索機能の実装

##動作確認手順
講師一覧画面 > チャプター&レッスン一覧画面 > 受講生一覧画面
http://localhost:3000/instructor/course/students?course_id=1

上記画面で検索機能が動くか確認

## 考慮してほしいこと
下記の通りリクエストのルールを変更
backend/laravelapp/app/Http/Requests/Instructor/StudentIndexRequest.php
public function rules()
    {
        return [
            'course_id' => ['required', 'integer', 'exists:courses,id'],
            'per_page' => ['integer', 'min:1'],
            'page' => ['integer', 'min:1'],
            'sort_by' => ['string', new IndexSortByRule()],
            'order' => ['string', 'in:asc,desc'],
            'input_text' => ['nullable', 'string'],
            'start_date' => ['nullable', 'date_format:Y-m-d'],
            'end_date' => ['nullable', 'date_format:Y-m-d'],
        ];
    }
## 確認してほしいこと
特になし

2024-03-09 02:56 UTC, Hikaru-Giannis requested changes

2024-03-09 02:56 UTC, Hikaru-Giannis commented on features/instructor-students/hooks/useFetchInstructorStudents.ts
> +    end_date: "",
`undefined`を許容して、APIリクエスト前にデータの検証を行い、空文字やundefinedの場合はパラメータに含めなければ良いと思ったのですが、いかがでしょう？

デフォルトで、`input_text`,`start_date`,`end_date`を空文字で送ることに違和感を感じたので提案でした！
APIはなるべく適切な型に沿って検証したいので、下手にnullableや空文字を許容は避けたいことも理由でした。

2024-03-09 02:56 UTC, Hikaru-Giannis commented on features/instructor-students/hooks/useFetchInstructorStudents.ts
> +    end_date: "",
その場合、`getFetchUrl`も変更する必要があるかと思います。
一度、検討して試していただけると嬉しいです！


```ts
const getFetchUrl = (
  courseId: string | string[] | undefined,
  params: Params
) => {
  const { per_page, page, sort_by, order, input_text, start_date, end_date } =
    params;

  // undefinedの場合は、URLSearchParamsに含めない
  const searchParams = new URLSearchParams();
  searchParams.append('per_page', String(per_page));
  searchParams.append('page', String(page));
  searchParams.append('sort_by', sort_by);
  searchParams.append('order', order);
  if (input_text) {
    searchParams.append('input_text', input_text);
  }
  if (start_date) {
    // YYYY-MM-DD HH:MM:SS形式に変換
    const startDate = format(new Date(start_date), 'yyyy-MM-dd 00:00:00');
    searchParams.append('start_date', startDate);
  }
  if (end_date) {
    // YYYY-MM-DD HH:MM:SS形式に変換
    const endDate = format(new Date(end_date), 'yyyy-MM-dd 23:59:59');
    searchParams.append('end_date', endDate);
  }

  return courseId
    ? `/api/v1/instructor/course/${courseId}/student/index?${new URLSearchParams(
        searchParams
      )}`
    : null;
};
```

2024-03-09 02:56 UTC, Hikaru-Giannis commented on package-lock.json
パッケージ管理ツールに、`yarn`を利用していたのでこちらは不要かと思います...！

2024-03-09 05:53 UTC, kaji514 commented on features/instructor-students/hooks/useFetchInstructorStudents.ts
> +    end_date: "",
ほぼ上記の通り修正しました。確認お願いします。

2024-03-09 05:54 UTC, kaji514 commented on package-lock.json
コミットから外しました。自分はnpm インストールだとうまくいきました。
確か、youtubeの説明ではyarnでもnpmでもどちらでも良いとの説明があった気がします。

2024-03-10 05:34 UTC, Hikaru-Giannis commented on features/instructor-students/hooks/useFetchInstructorStudents.ts
> +  end_date?: string | null;
これらは省略可能と定義している、かつ省略する場合はundefiendとしているので、nullを許容する必要性はないかと感じたのですがいかがでしょう？

2024-03-10 11:25 UTC, kaji514 commented on features/instructor-students/hooks/useFetchInstructorStudents.ts
> +  end_date?: string | null;
修正しました。
確かにnullの必要性はありませんでした

2024-03-10 12:47 UTC, Hikaru-Giannis commented on features/instructor-students/components/StudentsSearchForm.tsx
> +};
date-fnsというライブラリを使っているので、そちらのユーティリティ関数を使うといいと思います！
https://date-fns.org/

2024-03-10 13:03 UTC, kaji514 commented on features/instructor-students/components/StudentsSearchForm.tsx
> +};
ユーティリティ関数を使用しました。今後使うようにします。

2024-03-10 14:10 UTC, Hikaru-Giannis commented on features/instructor-students/components/StudentsSearchForm.tsx
> +};
ライブラリに依存したユーティリティ関数とは疎結合にしたいとかであれば、ラッパー関数で実装するとかもありかなと思います！date-fnsを使わなくなったら、これらの関数をまとめて改修しなければならないので...。
要するにユーティリティ関数を使うと便利だけど、上のような問題があるということをお伝えしたかったです！

2024-03-10 14:11 UTC, Hikaru-Giannis approved these changes

2024-03-10 14:11 UTC, merged