add:レッスン編集画面 プレビューボタンを押した先の画面作成
yukihiroLaravel/juko_next pull request #45
Opened 2024-03-18 04:47 UTC by kaji514

## issue
https://gut-familie.atlassian.net/browse/JKA-762

## 概要
React レッスン編集画面 プレビューボタンを押した先の画面作成

##動作確認手順
① 講座一覧　>　チャプター&レッスン一覧　>　PHPとは？
http://localhost:3000/instructor/lesson/edit?course_id=1&chapter_id=1&lesson_id=11
② プレビューボタンを押下する。
③下記（プレビュー画面）が新規タブで作成される
http://localhost:3000/instructor/lesson/preview?courseId=1&chapterId=1&lessonId=1
④挙動確認

## 考慮してほしいこと
特になし
## 確認してほしいこと
とりあえず動くように作成しました。リファクタリングすべき箇所もあると思うので教えてほしい。

2024-03-19 00:50 UTC, Hikaru-Giannis requested changes

2024-03-19 00:50 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +`;
Buttonのコンポーネントは、`components/atoms/Button/Button.tsx`のpropsで一貫性を持たせているので、拡張はなるべく避けるとコンポーネントの保守性につながると思います！Figmaの画面は受講生が作成しているので、コンポーネントのスタイルの一貫性は保たれていないので、厳密でなくて良いです。
他の実装で、まだ統一できていないButtonコンポーネントがある場合は、負債となっている状況でした。

もし、レスポンシブでフォントサイズを変更したい場合は、メディアクエリの利用は間違いではないのですが、デザイン重視ではない限りは、PC/モバイル判定処理を行なってその変数の値によって、Buttonへ渡すpropsのサイズを動的に変える方が利点が多いです！ただ、PCとモバイルでデザインが大きく変わるなどの場合は話が変わってきます。

2024-03-19 00:50 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +  };
コンポーネントの処理内で型定義は、コンポーネントの責務から外れた処理ですので、責めてコンポーネント外に記述するべきかと思いました！

このステータスの型定義は、`features/lesson-attendance/types/LessonAttendance.ts`でしているので、ここにステータスの型定義をしてエクスポートして、それを参照するようにしても良いかと思いました！

2024-03-19 16:01 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +`;
上記修正しました

2024-03-19 16:02 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +  };
型定義をしてエクスポートして、それを参照するようにしました

2024-03-20 11:44 UTC, Hikaru-Giannis requested changes

2024-03-20 11:44 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +        }
今回サイドバーは、動作する必要がないのでこちらは不要かと思います！

2024-03-20 11:44 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +  };
LessonとLessonの進捗状態をそれぞれ状態で管理するのは、保守性が落ちるのとコードの複雑性が上がってしまうので、一緒に状態管理した方が良いかと思います！

TypeScriptの型はインターセクション型を用いることで、定義することが可能です。
[参考記事](https://typescriptbook.jp/reference/values-types-variables/intersection)

```ts
const [currentLesson, setCurrentLesson] = useState<
    | (Lesson & {
        lessonAttendance: LessonAttendance;
      })
    | null
  >(null);
```

2024-03-20 11:44 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +const STATUS_COMPLETED_ATTENDANCE = 'completed_attendance';
こちらもコンポーネントファイルで定数定義は基本的に避けた方が良いです！
他でレッスン進捗状態を管理するときに同様のコードを記述することになり、分散してしまいます。
こちらも`features/lesson-attendance/types/LessonAttendance.ts`で定義してエクスポートすると再利用することができるようになるかと思います！

2024-03-20 11:44 UTC, Hikaru-Giannis commented on features/lesson-attendance/types/LessonAttendance.ts
> +};
サーバーサイドでこのような主キーをキーに辞書リストを作成することがありますが、フロントエンドはまずは次のような構造からアプローチすると個人的には保守しやすいコードになると思います！

```ts
  {
    lesson_attendance_id: 1,
    status: 'before_attendance'
  }
```

そうして、各レッスンの進捗を集約化させると最終的に次のようにするのが良いかと感じます。

```ts
export type LessonAttendance = {
  lesson_attendance_id: number;
  status: LessonAttendanceStatus;
};

export type LessonAttendanceStatus =
  | typeof STATUS_BEFORE_ATTENDANCE
  | typeof STATUS_IN_ATTENDANCE
  | typeof STATUS_COMPLETED_ATTENDANCE;

export const STATUS_BEFORE_ATTENDANCE = 'before_attendance';
export const STATUS_IN_ATTENDANCE = 'in_attendance';
export const STATUS_COMPLETED_ATTENDANCE = 'completed_attendance';
```

2024-03-20 11:44 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +          setCurrentLesson(initialLesson);
レッスンの進捗状態を同一管理するので、あればこの時点で初期レッスン進捗ステータスを同時に設定する必要があります！
今回はプレビューで、DBのデータとの整合性とかを厳密に合わせる必要がないので、次のように仮で`id=1`にしておくだけで良いと感じます。


```ts
        setCurrentLesson({
          ...initialLesson,
          lessonAttendance: {
            lesson_attendance_id: 1,
            status: 'before_attendance',
          },
        });
```

2024-03-20 11:44 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +    setCurrentLesson(newLesson);
ここもレッスンの進捗状態を同一管理するので、あればこの時点で初期レッスン進捗ステータスを同時に設定する必要があります！

2024-03-20 12:07 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +        }
修正しました

2024-03-21 10:32 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +const STATUS_COMPLETED_ATTENDANCE = 'completed_attendance';
修正しました。

2024-03-21 10:32 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +  };
修正しました

2024-03-21 10:36 UTC, kaji514 commented on features/lesson-attendance/types/LessonAttendance.ts
> +};
修正しました

2024-03-21 10:36 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +          setCurrentLesson(initialLesson);
修正しました

2024-03-21 10:36 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +    setCurrentLesson(newLesson);
修正しました

2024-03-21 13:58 UTC, Hikaru-Giannis requested changes

2024-03-21 13:58 UTC, Hikaru-Giannis commented on features/lesson-attendance/types/LessonAttendance.ts
LessonAttendanceは次のように書き換えれませんか？
なるべく状態の文字列とかは、集約して管理して状態が追加、変更、削除があるときに対応しやすくしたいです！

```ts
export type LessonAttendance = {
  lesson_attendance_id: number;
  status: LessonAttendanceStatus;
};

```

2024-03-21 13:58 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +    | undefined;
型定義は、コンポーネント関数の外で定義しておきましょう。
理由としては、コンポーネント関数内で、型の定義であることが一見わかりづらいためでした。

```tsx
type LessonList =
  | (Lesson & {
      lessonAttendance: LessonAttendance;
      isCurrentLesson: boolean;
    })
  | undefined;

const Index: NextPage = () => {
...
```

2024-03-21 13:58 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +import { number } from "yup";
こちらは参照していないと思うので、不要なインポートは削除するようにお願いします！

2024-03-21 13:58 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +  });
errorとmutateは参照していないので、取得する必要はないです！

2024-03-21 13:58 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +                    </div>
これは生徒側の実装もそのままの状態なので修正しなくてもいいのですが、`margin`ではなく`flexbox`の`gap`でスペースを確保する方がおそらく良いです。

理由としては、gapで指定した方がmarginよりも一貫したスペースを維持するのに最適だったためでした！

2024-03-21 13:58 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +        });
なるべくTypeScriptでのletによる変数定義は避けた方が良いです！
理由としては、constは一度定義すると再代入できないため、バグの可能性を減らしたり、変数の誤用を防ぐことに繋がります。

この実装のコードだと次のコードに書き換えることができると思ったのですが、いかがでしょう？

```tsx
if (lessonList.length === 0) {
        const initialLessonList = chapter.lessons.map((lesson) => {
          return {
            ...lesson,
            lessonAttendance: {
              lesson_attendance_id: 1,
              status: LESSON_ATTENDANCE_STATUS.STATUS_BEFORE_ATTENDANCE,
            },
            isCurrentLesson: lesson.lesson_id === lessonId,
          };
        });
        if (initialLessonList) {
          setLessonList(initialLessonList);
        }
      }
```

2024-03-21 13:58 UTC, Hikaru-Giannis commented on pages/instructor/lesson/preview/index.tsx
> +  }, [chapter, lessonList, lessonId]);
useEffectの依存配列は、当初のchapter=undefinedの状態から、データを取得した後の最初の一度だけで良いと思うので、chapterだけで問題がないと思ったのですがいかがでしょうか？

2024-03-21 15:53 UTC, kaji514 commented on features/lesson-attendance/types/LessonAttendance.ts
すみません見落としていました。修正しました。

2024-03-21 15:56 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +    | undefined;
修正しました。

2024-03-21 15:57 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +import { number } from "yup";
修正しました

2024-03-21 16:06 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +  });
修正しました

2024-03-21 16:09 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +  }, [chapter, lessonList, lessonId]);
修正しました

2024-03-21 16:19 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +        });
修正しました

2024-03-21 16:22 UTC, kaji514 commented on pages/instructor/lesson/preview/index.tsx
> +                    </div>
修正しました

2024-03-22 19:55 UTC, Hikaru-Giannis approved these changes

2024-03-24 10:28 UTC, merged