Feature/kaji/jka 767
yukihiroLaravel/juko_next pull request #47
Opened 2024-04-03 09:24 UTC by kaji514

## issue
https://gut-familie.atlassian.net/browse/JKA-767

## 概要
React 講師側 受講生詳細画面の作成

##動作確認手順
① 受講生一覧　>　受講生テーブルの行をクリック
http://localhost:3000/instructor/course/student/2?course_id=1
要件はチケットに記載

## 考慮してほしいこと
特になし
## 確認してほしいこと
特になし

2024-04-03 12:51 UTC, Hikaru-Giannis requested changes
全体通して、完成度高く実装できていると思います！
気になったのが、marginでスペース指定している箇所がいくつか見受けられたので、最初はなるべく要素のpaddingか、flexのgapを利用するようにして、どうしても例外的な箇所でmarginを取り入れると保守性もよくなる実装になるかと感じました！

2024-04-03 12:51 UTC, Hikaru-Giannis commented on pages/instructor/course/student/[id].tsx
> +          </div>
marginでスペースを指定するよりは、`flex column`で`gap`の方がコンテンツのスペースをレスポンシブを考慮して、一貫性を保てるのでなるべく`flex column`を使うようにしましょうか！

ただし、例外的なデザインはあることは理解いただければと思います！

2024-04-03 12:51 UTC, Hikaru-Giannis commented on features/instructor-students/components/StudentAttendanceStatusCard.tsx
> +      <h2 className="text-xl font-semibold md:text-2xl">学習状況</h2>
ここは、Typography を使ってほしいです！
もし適切なコンポーネントのサイズが適切でなければ、Typographyコンポーネントの実装を変更して問題ありません。

2024-04-03 12:51 UTC, Hikaru-Giannis commented on features/instructor-students/components/StudentDetailCard.tsx
> +      <h2 className="text-xl font-semibold md:text-2xl">基本情報</h2>
ここも、Typography を使ってほしいです！
もし適切なコンポーネントのサイズが適切でなければ、Typographyコンポーネントの実装を変更して問題ありません。

2024-04-03 12:51 UTC, Hikaru-Giannis commented on pages/instructor/course/student/[id].tsx
> +  });
パラメータの型が、string | string[] | undefined になってしまうと使い回ししづらいことに気づいたので、次のように型がstirngの時だけの処理で値を再定義すると良いと思いました！

```tsx
  const courseId =
    typeof course_id === 'string' ? parseInt(course_id) : undefined;
```

2024-04-03 12:51 UTC, Hikaru-Giannis commented on pages/instructor/course/student/[id].tsx
> +  });
他のHooksで既に修正している箇所も本当は治したいです...。

2024-04-03 12:51 UTC, Hikaru-Giannis commented on pages/instructor/course/student/[id].tsx
> +  });
実はTypeScriptのasによる型アサーションはなるべく避けるべきだということを理解いただければと思います！

2024-04-03 12:51 UTC, Hikaru-Giannis commented on components/atoms/Table/TableRow.tsx
> +  onClick?: React.MouseEventHandler<HTMLTableRowElement>;
onClickは個人の所感としてイベントの詳細にアクセスする必要性はあまりないため、何かの動作をトリガーするだけで良い場合は、onClick?: () => void; で良いと思います！

2024-04-03 13:49 UTC, kaji514 commented on pages/instructor/course/student/[id].tsx
> +          </div>
上記修正しました

2024-04-04 13:38 UTC, kaji514 commented on features/instructor-students/components/StudentAttendanceStatusCard.tsx
> +      <h2 className="text-xl font-semibold md:text-2xl">学習状況</h2>
上記修正しました

2024-04-04 13:40 UTC, kaji514 commented on features/instructor-students/components/StudentDetailCard.tsx
> +      <h2 className="text-xl font-semibold md:text-2xl">基本情報</h2>
上記修正しました。

2024-04-04 13:50 UTC, kaji514 commented on pages/instructor/course/student/[id].tsx
> +  });
新規で作成したcomponentだけcourseIdの型をnumber | undifinedにしました。

2024-04-04 13:55 UTC, kaji514 commented on components/atoms/Table/TableRow.tsx
> +  onClick?: React.MouseEventHandler<HTMLTableRowElement>;
修正しました。

2024-04-06 09:01 UTC, Hikaru-Giannis requested changes

2024-04-06 09:01 UTC, kou-tech commented on features/instructor-students/components/StudentAttendanceStatusCard.tsx
> +  };
この辺りは別のコンポーネントの話として切り出せそうなので、StudentAttendanceStatusCard の関数コンポーネント外で下の方に次のように定義すると良いかもしれないです！あとは、可能であればany型は避けるようにしましょう。型の恩恵を受けれなくなるので、最終手段で理解していただければと思います！

```tsx
const renderCustomizedLabel = (props: {
  x?: number | string | undefined;
  y?: number | string | undefined;
  value?: number | string | undefined;
}) => {
  const chartWidth = 400;
  const { y, value } = props;

  const yValue = (() => {
    if (typeof y === 'undefined') return 0;
    if (typeof y === 'string') {
      return parseInt(y);
    }
    return y;
  })();

  return (
    <text x={chartWidth - 30} y={yValue + 15} fill="#666" textAnchor="end">
      {`${value}％`}
    </text>
  );
};

```

2024-04-06 09:01 UTC, Hikaru-Giannis commented on features/instructor-students/components/StudentDetailCard.tsx
> +        </div>
このコードでは、Figmaの画面のようなラベルと値の要素の幅がバラバラのため見た目の一貫性が取れていないかと思いました！それを解決するために、グリッドシステムを活用すると良いと思います！

2024-04-06 09:01 UTC, Hikaru-Giannis commented on features/instructor-students/components/StudentDetailCard.tsx
> +        </div>
strongタグは、コンテンツの意味的な強調（重要性の強調）に使うべきで、視覚的なスタイリング（例：太字）のためだけにstrongを使うのは、セマンティックなHTMLの観点からは最適ではないです。
見た目を太字にする目的であれば、Tailwind CSSのfont-semiboldクラスを使用すると良いかと思います！

2024-04-06 09:01 UTC, Hikaru-Giannis commented on features/instructor-students/components/StudentDetailCard.tsx
> +        </div>
p（段落）要素はテキストのブロックを意味し、ここでの使用は内容をセマンティックにより適切に表現できます。divだとより一般的なコンテナであり、特定の意味を持たないため、pの方がこのコンテキストとして適しているかと思いました！

2024-04-09 14:37 UTC, kaji514 commented on features/instructor-students/components/StudentAttendanceStatusCard.tsx
> +  };
tudentAttendanceStatusCard の関数コンポーネント外で下の方に次のように定義してみました。

2024-04-09 14:56 UTC, kaji514 commented on features/instructor-students/components/StudentDetailCard.tsx
> +        </div>
上記修正しました！

2024-04-11 11:58 UTC, Hikaru-Giannis approved these changes

2024-04-11 11:58 UTC, Hikaru-Giannis commented on features/instructor-students/components/StudentDetailCard.tsx
> +        <div className="grid grid-cols-2 gap-4 px-4 pb-4">
感覚的な話なので、間違ってはいないのですが、40行目は次のコードだと個人的に良いと思いしたので、修正しました。

```tsx
        <div className="grid grid-cols-[auto,1fr] gap-x-4 gap-y-3 p-3">
```

2024-04-17 13:29 UTC, kaji514 commented on features/instructor-students/components/StudentDetailCard.tsx
> +        <div className="grid grid-cols-2 gap-4 px-4 pb-4">
ありがとうございます。参考にします。

2024-04-21 10:03 UTC, merged