Feature/kaji/jka 778
yukihiroLaravel/juko_next pull request #49
Opened 2024-04-09 09:19 UTC by kaji514

## issue
https://gut-familie.atlassian.net/browse/JKA-778

## 概要
React 講師側 お知らせ一覧画面

##動作確認手順
① お知らせ一覧
http://localhost:3000/instructor/notifications?course_id=1
要件はfigmaに記載

## 考慮してほしいこと
特になし
## 確認してほしいこと
特になし

2024-04-10 11:16 UTC, kou-tech requested changes
お知らせ登録は次のIssueだと認識でよろしいですか？

2024-04-10 11:16 UTC, kou-tech commented on features/notification/components/NotificationsTable.tsx
> +          </TableCell>
他の実装も修正すべきことかもしれませんが、TableCellの詳細の実装は<td>になっています。
しかし、この箇所はターブルのヘッダーセルがセマンティクス的に正しいのと、その場合は勝手に中央寄せになります。
次のように実装を修正お願いできますか？

th : テーブルヘッダーセル
td : テーブルデータセル

ちなみにtheadは、<thead>タグはテーブルのヘッダー部分全体を定義しており、また別です。

2024-04-10 14:20 UTC, kaji514 commented on features/notification/components/NotificationsTable.tsx
> +          </TableCell>
修正しました！

2024-04-11 11:43 UTC, Hikaru-Giannis approved these changes

2024-04-14 12:35 UTC, kaji514 commented
> お知らせ登録は次のIssueだと認識でよろしいですか？

はい、その認識の通りです！

2024-04-15 11:28 UTC, Hikaru-Giannis approved these changes

2024-04-15 11:28 UTC, merged