add:講師側のお知らせ登録機能の実装
yukihiroLaravel/juko_next pull request #51
Opened 2024-04-22 07:55 UTC by kaji514

## issue
https://gut-familie.atlassian.net/browse/JKA-817

## 概要
React 講師側 受講生お知らせ登録画面の作成

##動作確認手順
① お知らせ一覧　>　お知らせ登録ボタンを押下
http://localhost:3000/instructor/notifications

要件はチケットに記載

## 考慮してほしいこと
特になし
## 確認してほしいこと
特になし

2024-04-23 11:33 UTC, Hikaru-Giannis requested changes

2024-04-23 11:33 UTC, Hikaru-Giannis commented on features/notification/components/NotificationRegisterForm.tsx
> +          </select>
講師の講座セレクトボックスを１コンポーネント化して良いと思います！
理由としては、講座情報取得するHooksとかをそのコンポーネントに移譲することができるからです。

2024-04-23 11:33 UTC, Hikaru-Giannis commented on features/notification/components/NotificationRegisterForm.tsx
> +    content: '',
存在しないcourse_idを-1とするのは避けて、nullにしましょう。
値が決まっていないフィールドに対して、初期値を渡す必要性がない可能性も考慮すると良いかもです。

2024-04-23 11:33 UTC, Hikaru-Giannis commented on features/notification/components/NotificationRegisterForm.tsx
> +    isSending.current = true;
最近気づいたのですが、React Hook FormにisSubmittingという値を参照できるため、そちらで送信制御すると良さそうです！

2024-04-23 11:33 UTC, Hikaru-Giannis commented on features/notification/components/NotificationRegisterForm.tsx
> +                  {...register('type', { required: true })}
バリデーションはyupで定義しているので、React Hook Formのバリデーションの記述は不要かと思います！
他の記述箇所も同様の対応をお願いします！

2024-04-23 11:33 UTC, Hikaru-Giannis commented on features/notification/components/NotificationRegisterForm.tsx
> +                  value="once"
Notificationのtypeは定数にして、定義しましょうか！
LessonAttendanceのステータスと同様の実装とするイメージです。

2024-04-23 11:33 UTC, Hikaru-Giannis commented on features/notification/components/NotificationRegisterForm.tsx
> +            />
このシステムで日付のフィールドはDatepickerを使っているので、Datepickerを利用したフィールドで実装をお願いします。
他の日付フィールドも同様の対応をお願いします。

2024-04-28 05:49 UTC, kaji514 commented on features/notification/components/NotificationRegisterForm.tsx
> +          </select>
一応コンポーネント化しましたが型指定がanyになっているのでどのようにすれば良いでしょうか？

2024-07-05 12:54 UTC, mtakk commented on features/notification/components/NotificationRegisterForm.tsx
> +    content: '',
ここはnullでなく-1や0等でいいかと思うのですがどうでしょうか？
というのもyup.number().nullable()などでは解決できず、Pickしてきている型の根本であるNotification.tsでcourse_id: number | null;に変更しないといけないからです。

2024-07-05 13:05 UTC, mtakk commented on features/notification/components/NotificationRegisterForm.tsx
> +                  {...register('type', { required: true })}
削除しました！

2024-07-05 13:17 UTC, mtakk commented on features/notification/components/NotificationRegisterForm.tsx
> +                  value="once"
定数化しました！

2024-07-07 11:29 UTC, mtakk commented on features/notification/components/NotificationRegisterForm.tsx
> +            />
Datepickerを使うように修正しました！

2024-07-07 11:40 UTC, mtakk commented on features/notification/components/NotificationRegisterForm.tsx
> +    isSending.current = true;
isSubmittingを使った形に変えました！

2024-07-11 16:18 UTC, mtakk commented on features/notification/components/NotificationRegisterForm.tsx
> +          </select>
今回は汎用的なセレクトボックスにしたので講座情報取得するHooksは、変わらずNotificationRegisterFormで呼び出す方針にしました！
取得した情報をoptionタグのlabelとvalueに入れるときにどんな値を入れるかはhooksによって変わるので、呼び出しもとで制御してもらうことにしました。

2024-07-12 19:18 UTC, Hikaru-Giannis requested changes

2024-07-12 19:18 UTC, kou-tech commented on components/atoms/SelectBox/SelectBox.tsx
今後、このディレクトリで`SelectBox`に関連するモジュールを管理することになりますので、他のコンポーネント同様に`index.ts`を作成し、単一のインポートステートメントで複数のエクスポートをまとめてインポートできるようにお願いします！

2024-07-12 19:18 UTC, kou-tech commented on components/atoms/SelectBox/SelectBox.tsx
> +      id="courseName"
`id="courseName"`は、特定のドメインに依存しているコンポーネントになるので、ここで固定値は避けた方が良いです！
propsで受け取れるようにしましょう。

2024-07-12 19:18 UTC, Hikaru-Giannis commented on components/atoms/SelectBox/SelectBox.tsx
> +      className="block mt-1 w-full rounded border-gray-300 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
他の実装で誤っている可能性があるという前提でお聞きください！
ここで`block`、`margin`、`w-full`を指定しまうと、再利用性が落ちる可能性があります。
例えば、親コンポーネントが`flex`を使いたい時など、レイアウトが崩れてしまう可能性があるので、避けた方が良いです。

最近良い記事があったので、共有します！
https://qiita.com/uhyo/items/e51fd3850b6a0a3d055a?utm_campaign=post_article&utm_medium=twitter&utm_source=twitter_share

2024-07-12 19:18 UTC, Hikaru-Giannis commented on components/atoms/SelectBox/SelectBox.tsx
> +  register?: UseFormRegister<any>;
型指定に`any`は避けたい(`any`を撲滅するlinterが開発されるほど)ので、私がよくやる方法を共有します！
というのも次のように`register`を展開した状態で渡す方法ですね！
少し前の記事ですが、参考になるかもしれません！
https://zenn.dev/yodaka/articles/cc909b405915c6

```tsx
import { UseFormRegisterReturn } from 'react-hook-form';

...
type SelectBoxProps<T extends string | number> = {
  ...
  register?: UseFormRegisterReturn;
  ...
};
...
<select
      {...register}
    >
```

2024-07-12 19:18 UTC, Hikaru-Giannis commented on components/atoms/SelectBox/SelectBox.tsx
> +type SelectBoxProps<T extends string | number> = {
いわゆるWeb標準に従うのであれば、値は文字列として扱うのが一般的なので、数値でも基本的に文字列で扱う方が都合がいいことが多いです！
APIリクエストや計算が必須なケースにおいて、その箇所で型変換するとか！

ケースバイケースなので、もちろん数値を許容することもありますが、最初から数値を許容すると保守が難しくなったりするので、現状のidの数値を扱うだけであれば、一旦文字列で対応いただきたいです！

2024-07-12 19:18 UTC, Hikaru-Giannis commented on components/atoms/SelectBox/SelectBox.tsx
> +      className="block mt-1 w-full rounded border-gray-300 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
`focus:ring-opacity-50`がtailwindのv3で新しい記述に変更されているらしいです。
古い記法にしておく必要はないので、対応をお願いします！
https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/migration-from-tailwind-2.md

2024-07-13 11:52 UTC, mtakk commented on components/atoms/SelectBox/SelectBox.tsx
> +      id="courseName"
そうですね！修正しました！

2024-07-13 12:47 UTC, mtakk commented on components/atoms/SelectBox/SelectBox.tsx
> +  register?: UseFormRegister<any>;
なるほど、これで消せるんですね！修正しました！

2024-07-13 12:52 UTC, mtakk commented on components/atoms/SelectBox/SelectBox.tsx
> +type SelectBoxProps<T extends string | number> = {
なるほどありがとうございます！文字列指定にしました！

2024-07-14 06:40 UTC, mtakk commented on components/atoms/SelectBox/SelectBox.tsx
> +      className="block mt-1 w-full rounded border-gray-300 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
> 他の実装で誤っている可能性があるという前提でお聞きください！....
marginは消しました！
block,w-fullですが、ここは呼び出す側でdivで囲いwidthを指定するなどすれば良いと思うのですがどうでしょうか？逆にここでw-fullにしないと親要素に合わせて横幅を引き伸ばすことができないかなと思います...！

> focus:ring-opacity-50がtailwindのv3で新しい記述に変更されているらしいです。
focus:ring-opacity/50に変更しました！

2024-07-14 06:52 UTC, mtakk commented on components/atoms/SelectBox/SelectBox.tsx
なるほど、確かにindex.tsでいいかと思いましたが、他に合わせてindex.tsxを作りました！

2024-07-14 12:21 UTC, Hikaru-Giannis commented on components/atoms/SelectBox/SelectBox.tsx
> +      className="block mt-1 w-full rounded border-gray-300 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
> block,w-fullですが、ここは呼び出す側でdivで囲いwidthを指定するなどすれば良いと思うのですがどうでしょうか？

確かにそれで良さそうです！ただし、blockは不要ではありませんか？

2024-07-14 19:56 UTC, Hikaru-Giannis commented
口頭で説明したこと
- 現状のセレクトボックスを残しつつ、講座のセレクトボックスを実装する。
- `margin`の多様は避けて、`flex`を極力利用し、デザインの一貫性を保つ。
- セレクトボックスに未選択の選択肢を入れる。
- セレクトボックスにborderとpaddingを追加する。

2024-07-15 05:38 UTC, mtakk commented on components/atoms/SelectBox/SelectBox.tsx
> +      className="block mt-1 w-full rounded border-gray-300 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
block不要なので消しました！

2024-07-15 09:15 UTC, Hikaru-Giannis requested changes
日付のバリデーションメッセージのテキスト修正と表示箇所の調整をお願いします！
<img width="415" alt="Screenshot 2024-07-15 at 18 15 02" src="https://github.com/user-attachments/assets/4ec45a14-c51d-4b89-ae2f-6c503fe27006">

> 日付のバリデーションメッセージのテキスト修正と表示箇所の調整をお願いします！

すいません、修正しました！

2024-07-16 11:08 UTC, Hikaru-Giannis approved these changes

2024-07-16 14:11 UTC, merged