JKA-544 タイトル押下時に講座一覧画面に遷移（三井）
yukihiroLaravel/juko_next pull request #52
Opened 2024-05-22 12:56 UTC by mtakk

## task
- JKA-544 

## 概要
- React 画面左上「受講管理アプリ」の文字を押したときに/courses 講座一覧画面に遷移するようにする ※受講生側

## 動作確認手順
- 受講生側でログインする
- 任意のページに遷移し、左上の「受講管理アプリ」の文字をクリックすると、講座一覧画面に遷移する

## 確認してほしいこと
- 特にないです

2024-05-23 12:13 UTC, Hikaru-Giannis requested changes
`Header`コンポーネントでリンクを設定してしまうと、生徒でログイン時は問題ないのですが、講師でログイン時は遷移先が異なるので、どちらも正常なリンクを設定できるように修正いただきたいです！

2024-06-15 05:09 UTC, mtakk commented
> `Header`コンポーネントでリンクを設定してしまうと、生徒でログイン時は問題ないのですが、講師でログイン時は遷移先が異なるので、どちらも正常なリンクを設定できるように修正いただきたいです！

生徒側と講師側で遷移先が変わるように修正しました！

2024-06-15 08:23 UTC, Hikaru-Giannis requested changes

2024-06-15 08:23 UTC, Hikaru-Giannis commented on components/organisms/header/presentations/Header.tsx
> +          </Link>
ヘッダーのタイトルのmarginが効いていない気がしますので、修正をお願いします！
<img width="1458" alt="Screenshot 2024-06-15 at 17 06 10" src="https://github.com/yukihiroLaravel/juko_next/assets/64859506/f3457fe1-1798-4622-b179-c228dc61ec69">

2024-06-15 08:23 UTC, Hikaru-Giannis commented on components/organisms/header/presentations/Header.tsx
> +          </Link>
挙動としては問題がないのですが、HTMLの標準に従いaタグにhrefを指定した方が良いらしいです！
これらは、SEOなどに影響があるとか...。
私も最近知ったのですが、次のドキュメントを参考に修正のほどよろしくお願いします🙇‍♂️
[ドキュメント](https://nextjs-ja-translation-docs.vercel.app/docs/api-reference/next/link#%E5%AD%90%E3%81%8C-a-%E3%82%BF%E3%82%B0%E3%82%92%E3%83%A9%E3%83%83%E3%83%97%E3%81%99%E3%82%8B%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%81%AE%E5%A0%B4%E5%90%88)

2024-06-15 08:23 UTC, Hikaru-Giannis commented on components/organisms/header/presentations/Header.tsx
> +          </Link>
次のは今後の実装の参考程度に読んでください！

今回のケースであれば、propsからURLを渡して対応で問題ないかと思いますが、本来はタイトルのURLだけを変えるのにHeaderコンポーネントにpropsを渡したりすると将来的にpropsが肥大化し、保守性が落ちます。
タイトルコンポーネントを作成して、そのpropsだけを変えれると良いですよね。
そういった時のテクニックとして、render propsという方法があったりします。
ただReactの直感的な実装から少し変わるので、多用は厳禁でこういった方法もあるという程度でご理解いただければと思います！

2024-06-15 12:44 UTC, mtakk commented on components/organisms/header/presentations/Header.tsx
> +          </Link>
教えていただいた例を見て理解できました！ありがとうございます！

2024-06-15 13:05 UTC, Hikaru-Giannis approved these changes

2024-06-16 01:58 UTC, merged